# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_06IxMTMYQqHiATZFJoGG4bwUGVgM0_l
"""

import numpy as np

import pandas as pd

import seaborn as sns #using sns for "sns.lmplot" plotting

df = pd.read_csv("/content/drive/My Drive/PRSA_Data_Changping_20130301-20170228.csv")

df.describe

df1 = df.dropna()
print(df1)

df_binary.fillna(method ='ffill', inplace = True) #Deleteing NA vals from the data set

print(df1)

df_binary = df[['TEMP', 'CO']]#Using only temp and carbon monoxide columns as data

df_binary.columns = ['TEMP', 'CO']#Using only temp and carbon monoxide columns as data

df_binary.head()

sns.lmplot(x ="TEMP", y ="CO", data = df_binary, order = 2, ci = None, palette=dict(Yes="g", No="m"))#Using sns.lmplot to plot regression

df_binary500 = df_binary[:][:500]#Uisng only 500 poitns to redo regression line

df_binary500.fillna(method ='ffill', inplace = True) 
  
X = np.array(df_binary500['TEMP']).reshape(-1, 1)#reshaping x
y = np.array(df_binary500['CO']).reshape(-1, 1) #reshaping y
  
df_binary500.dropna(inplace = True)#Training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25) 
  
regr = LinearRegression()#Plotting the new regression line and printing the regression score 
regr.fit(X_train, y_train) 
print(regr.score(X_test, y_test))

y_pred = regr.predict(X_test) 
plt.scatter(X_test, y_test, color ='B') 
plt.plot(X_test, y_pred, color ='R') 
  
plt.show()